# Chapter 3: Numerical Calculations with Numpy

## Creating arrays

Numpy defines a new numeric datatype called the ndarray. Use import numpy or from numpy import \*. ndarrays can be created using the array() function.

In [8]:
from numpy import *

test_ndarray_1d = array([1,2,3])
test_ndarray_2d = array([[1, 2, 3],[4, 5, 6]])
test_ndarray_3d = array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])

print("test_ndarray_1d: ",test_ndarray_1d)
print("test_ndarray_1d.shape: ", test_ndarray_1d.shape)
print("test_ndarray_2d: ", test_ndarray_2d)
print("test_ndarray_2d.size: ", test_ndarray_2d.size)
print("test_ndarray_2d.shape: ", test_ndarray_2d.shape)
print("test_ndarray_3d:")
print(test_ndarray_3d)
print("test_ndarray_3d.size: ", test_ndarray_3d.size)
print("test_ndarray_3d.shape: ", test_ndarray_3d.shape)

test_ndarray_1d:  [1 2 3]
test_ndarray_1d.shape:  (3,)
test_ndarray_2d:  [[1 2 3]
 [4 5 6]]
test_ndarray_2d.size:  6
test_ndarray_2d.shape:  (2, 3)
test_ndarray_3d:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
test_ndarray_3d.size:  12
test_ndarray_3d.shape:  (2, 2, 3)


Alernatively, arange (start, stop, interval) and linspace (start, stop, count) can be used to create 1-D arrays. zeros(shape tuple) and ones (shape tuple) can also be used to create ndarrays.

Furthermore, meshgrid can be used to create the "mesh" which specifies positions in a dimensional vector space (think two-dimensional x-y grid)

In [15]:
x = arange(0,5.1)
y = arange(0,3.1)
z = arange(0,2.1)

(X,Y) = meshgrid(x,y)
print("X: \n",X)
print("Y: \n",Y)

(X,Y,Z) = meshgrid(x,y,z)
print("==================================")
print("X: \n",X)
print("Y: \n",Y)
print("Z: \n",Z)
print("X: \n",X)
print("X.shape: \n",X.shape)

X: 
 [[0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]]
Y: 
 [[0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 3.]]
X: 
 [[[0. 0. 0.]
  [1. 1. 1.]
  [2. 2. 2.]
  [3. 3. 3.]
  [4. 4. 4.]
  [5. 5. 5.]]

 [[0. 0. 0.]
  [1. 1. 1.]
  [2. 2. 2.]
  [3. 3. 3.]
  [4. 4. 4.]
  [5. 5. 5.]]

 [[0. 0. 0.]
  [1. 1. 1.]
  [2. 2. 2.]
  [3. 3. 3.]
  [4. 4. 4.]
  [5. 5. 5.]]

 [[0. 0. 0.]
  [1. 1. 1.]
  [2. 2. 2.]
  [3. 3. 3.]
  [4. 4. 4.]
  [5. 5. 5.]]]
Y: 
 [[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]]
Z: 
 [[[0. 1. 2.]
  [0. 1. 2.]
  [0. 1. 2.]
  [0. 1. 2.]
  [0. 1. 2.]
  [0. 1. 2.]]

 [[0. 1. 2.]
  [0. 1. 2.]
  [0. 1. 2.]
  [0. 1. 2.]
  [0. 1. 2.]
  [0. 1. 2.]]

 [[0.

The 3-d case is confusing because the first argument (x) is the second dimension of X,Y,Z, the second argument (y) is the first, and the third argment is the third dimension.